# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/liuyu/workspace/blockchain/miner/opencl-miner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/liuyu/workspace/blockchain/miner/opencl-miner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liuyu/workspace/blockchain/miner/opencl-miner/CMakeFiles /Users/liuyu/workspace/blockchain/miner/opencl-miner/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liuyu/workspace/blockchain/miner/opencl-miner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named beam-opencl-miner

# Build rule for target.
beam-opencl-miner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 beam-opencl-miner
.PHONY : beam-opencl-miner

# fast build rule for target.
beam-opencl-miner/fast:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/build
.PHONY : beam-opencl-miner/fast

beam/core/difficulty.o: beam/core/difficulty.cpp.o

.PHONY : beam/core/difficulty.o

# target to build an object file
beam/core/difficulty.cpp.o:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/core/difficulty.cpp.o
.PHONY : beam/core/difficulty.cpp.o

beam/core/difficulty.i: beam/core/difficulty.cpp.i

.PHONY : beam/core/difficulty.i

# target to preprocess a source file
beam/core/difficulty.cpp.i:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/core/difficulty.cpp.i
.PHONY : beam/core/difficulty.cpp.i

beam/core/difficulty.s: beam/core/difficulty.cpp.s

.PHONY : beam/core/difficulty.s

# target to generate assembly for a file
beam/core/difficulty.cpp.s:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/core/difficulty.cpp.s
.PHONY : beam/core/difficulty.cpp.s

beam/core/uintBig.o: beam/core/uintBig.cpp.o

.PHONY : beam/core/uintBig.o

# target to build an object file
beam/core/uintBig.cpp.o:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/core/uintBig.cpp.o
.PHONY : beam/core/uintBig.cpp.o

beam/core/uintBig.i: beam/core/uintBig.cpp.i

.PHONY : beam/core/uintBig.i

# target to preprocess a source file
beam/core/uintBig.cpp.i:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/core/uintBig.cpp.i
.PHONY : beam/core/uintBig.cpp.i

beam/core/uintBig.s: beam/core/uintBig.cpp.s

.PHONY : beam/core/uintBig.s

# target to generate assembly for a file
beam/core/uintBig.cpp.s:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/core/uintBig.cpp.s
.PHONY : beam/core/uintBig.cpp.s

beam/utility/common.o: beam/utility/common.cpp.o

.PHONY : beam/utility/common.o

# target to build an object file
beam/utility/common.cpp.o:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/utility/common.cpp.o
.PHONY : beam/utility/common.cpp.o

beam/utility/common.i: beam/utility/common.cpp.i

.PHONY : beam/utility/common.i

# target to preprocess a source file
beam/utility/common.cpp.i:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/utility/common.cpp.i
.PHONY : beam/utility/common.cpp.i

beam/utility/common.s: beam/utility/common.cpp.s

.PHONY : beam/utility/common.s

# target to generate assembly for a file
beam/utility/common.cpp.s:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beam/utility/common.cpp.s
.PHONY : beam/utility/common.cpp.s

beamStratum.o: beamStratum.cpp.o

.PHONY : beamStratum.o

# target to build an object file
beamStratum.cpp.o:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beamStratum.cpp.o
.PHONY : beamStratum.cpp.o

beamStratum.i: beamStratum.cpp.i

.PHONY : beamStratum.i

# target to preprocess a source file
beamStratum.cpp.i:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beamStratum.cpp.i
.PHONY : beamStratum.cpp.i

beamStratum.s: beamStratum.cpp.s

.PHONY : beamStratum.s

# target to generate assembly for a file
beamStratum.cpp.s:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/beamStratum.cpp.s
.PHONY : beamStratum.cpp.s

clHost.o: clHost.cpp.o

.PHONY : clHost.o

# target to build an object file
clHost.cpp.o:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/clHost.cpp.o
.PHONY : clHost.cpp.o

clHost.i: clHost.cpp.i

.PHONY : clHost.i

# target to preprocess a source file
clHost.cpp.i:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/clHost.cpp.i
.PHONY : clHost.cpp.i

clHost.s: clHost.cpp.s

.PHONY : clHost.s

# target to generate assembly for a file
clHost.cpp.s:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/clHost.cpp.s
.PHONY : clHost.cpp.s

crypto/sha256.o: crypto/sha256.c.o

.PHONY : crypto/sha256.o

# target to build an object file
crypto/sha256.c.o:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/crypto/sha256.c.o
.PHONY : crypto/sha256.c.o

crypto/sha256.i: crypto/sha256.c.i

.PHONY : crypto/sha256.i

# target to preprocess a source file
crypto/sha256.c.i:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/crypto/sha256.c.i
.PHONY : crypto/sha256.c.i

crypto/sha256.s: crypto/sha256.c.s

.PHONY : crypto/sha256.s

# target to generate assembly for a file
crypto/sha256.c.s:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/crypto/sha256.c.s
.PHONY : crypto/sha256.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/beam-opencl-miner.dir/build.make CMakeFiles/beam-opencl-miner.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... beam-opencl-miner"
	@echo "... beam/core/difficulty.o"
	@echo "... beam/core/difficulty.i"
	@echo "... beam/core/difficulty.s"
	@echo "... beam/core/uintBig.o"
	@echo "... beam/core/uintBig.i"
	@echo "... beam/core/uintBig.s"
	@echo "... beam/utility/common.o"
	@echo "... beam/utility/common.i"
	@echo "... beam/utility/common.s"
	@echo "... beamStratum.o"
	@echo "... beamStratum.i"
	@echo "... beamStratum.s"
	@echo "... clHost.o"
	@echo "... clHost.i"
	@echo "... clHost.s"
	@echo "... crypto/sha256.o"
	@echo "... crypto/sha256.i"
	@echo "... crypto/sha256.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

